FROM node:lts-alpine3.17 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY *.json ./

RUN npm install

COPY . .

RUN next build

FROM nginx:latest as server

EXPOSE 3000

COPY frontend.nginx.prod.conf /etc/nginx/nginx.conf

COPY --from=build /app/build /usr/share/nginx/html


CMD ["nginx", "-g", "daemon off;"]