version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    ports:
      - 7800:7800

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: "no"
    volumes:
      - ./backend/:/app
      - ./app-cache/:/app-cache
    expose:
      - "8080"
    depends_on:
      - database
    env_file:
      - project.env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    restart: "always"
    volumes:
      - ./frontend/:/app
      - next_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  next_node_modules:
